name: CI
on: [create, pull_request, push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed to make sure to proper git describe
      # This is a workaround for https://github.com/actions/checkout/issues/649
      - name: Fix fetched tag
        if: startsWith(github.ref, 'refs/tags/')
        run: /usr/bin/git -c protocol.version=2 fetch --prune --progress
            --no-recurse-submodules origin +"$GITHUB_REF:$GITHUB_REF"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python-docutils ruby-dev
          sudo gem install fpm
      - name: Build
        run: make PYTHON=python3 all deb
      - name: Archive package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: deb/git-hub_*.deb
          if-no-files-found: error
